kind: pipeline
type: docker
name: Test

steps:
- name: Test
  image: node:lts
  commands:
  - npm install
  - npm test

---
kind: pipeline
type: docker
name: Deploy



steps:
- name: Deployment
  image: alpine
  environment:
    USERNAME:
      from_secret: username
    Password:
      from_secret: password
    PUB_KEY:
      from_secret: PUB_KEY
  commands:
    - apk add --no-cache openssh-client sshpass
    - mkdir -p /root/.ssh/
    - echo $PUB_KEY > /root/.ssh/known_hosts
    - sshpass -p $password ssh $username@$ip
    - echo "Shutting down old instance"
    - cd teamspeak-monitoring-bot 
    - screen -X -S tsbot quit
    - echo "Getting new Version from master"
    - git pull
    - echo "Reinstalling modules"
    - npm ci
    - echo "Starting Bot"
    - screen -dm -S tsbot npm start  
  when:
    branch:
      - master