kind: pipeline
type: docker
name: Test

steps:
- name: Test
  image: node:lts
  commands:
  - npm install
  - npm test

---
kind: pipeline
type: docker
name: Deploy



steps:
- name: Stop The Bot
  image: appleboy/drone-ssh
  settings:
    host: 85.214.231.163
    username: 
      from_secret: username
    password:
      from_secret: password
    port: 22
  script:
    - cd teamspeak-monitoring-bot 
    - screen -X -S tsbot quit
    - git pull
    - rm -rf node_modules/
    - npm install
    - screen -dm -S tsbot npm start  
  when:
    branch:
      - master